# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MeasuringSessionReportProto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="MeasuringSessionReportProto.proto",
    package="biospectal",
    syntax="proto3",
    serialized_options=b"\n\032com.biospectal.io.protobuf",
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n!MeasuringSessionReportProto.proto\x12\nbiospectal"/\n\x06Sample\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x12\n\x06pixels\x18\x02 \x03(\x02\x42\x02\x10\x01"\xaa\x01\n\rRecordingData\x12"\n\x06result\x18\x01 \x01(\x0e\x32\x12.biospectal.Result\x12\r\n\x05start\x18\x02 \x01(\x03\x12\x16\n\x0erecordingStart\x18\x03 \x01(\x01\x12\x13\n\x0bsampleWidth\x18\x04 \x01(\x05\x12\x14\n\x0csampleHeight\x18\x05 \x01(\x05\x12#\n\x07samples\x18\x06 \x03(\x0b\x32\x12.biospectal.Sample*H\n\x06Result\x12\x0b\n\x07SUCCESS\x10\x00\x12\r\n\tOBPM_FAIL\x10\x02\x12\x15\n\x11QUALITY_THRESHOLD\x10\x03\x12\x0b\n\x07UNKNOWN\x10\x04\x42\x1c\n\x1a\x63om.biospectal.io.protobufb\x06proto3',
)

_RESULT = _descriptor.EnumDescriptor(
    name="Result",
    full_name="biospectal.Result",
    filename=None,
    file=DESCRIPTOR,
    create_key=_descriptor._internal_create_key,
    values=[
        _descriptor.EnumValueDescriptor(
            name="SUCCESS",
            index=0,
            number=0,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="OBPM_FAIL",
            index=1,
            number=2,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="QUALITY_THRESHOLD",
            index=2,
            number=3,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="UNKNOWN",
            index=3,
            number=4,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=271,
    serialized_end=343,
)
_sym_db.RegisterEnumDescriptor(_RESULT)

Result = enum_type_wrapper.EnumTypeWrapper(_RESULT)
SUCCESS = 0
OBPM_FAIL = 2
QUALITY_THRESHOLD = 3
UNKNOWN = 4


_SAMPLE = _descriptor.Descriptor(
    name="Sample",
    full_name="biospectal.Sample",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="timestamp",
            full_name="biospectal.Sample.timestamp",
            index=0,
            number=1,
            type=1,
            cpp_type=5,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="pixels",
            full_name="biospectal.Sample.pixels",
            index=1,
            number=2,
            type=2,
            cpp_type=6,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\020\001",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=49,
    serialized_end=96,
)


_RECORDINGDATA = _descriptor.Descriptor(
    name="RecordingData",
    full_name="biospectal.RecordingData",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="result",
            full_name="biospectal.RecordingData.result",
            index=0,
            number=1,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="start",
            full_name="biospectal.RecordingData.start",
            index=1,
            number=2,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="recordingStart",
            full_name="biospectal.RecordingData.recordingStart",
            index=2,
            number=3,
            type=1,
            cpp_type=5,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="sampleWidth",
            full_name="biospectal.RecordingData.sampleWidth",
            index=3,
            number=4,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="sampleHeight",
            full_name="biospectal.RecordingData.sampleHeight",
            index=4,
            number=5,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="samples",
            full_name="biospectal.RecordingData.samples",
            index=5,
            number=6,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=99,
    serialized_end=269,
)

_RECORDINGDATA.fields_by_name["result"].enum_type = _RESULT
_RECORDINGDATA.fields_by_name["samples"].message_type = _SAMPLE
DESCRIPTOR.message_types_by_name["Sample"] = _SAMPLE
DESCRIPTOR.message_types_by_name["RecordingData"] = _RECORDINGDATA
DESCRIPTOR.enum_types_by_name["Result"] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Sample = _reflection.GeneratedProtocolMessageType(
    "Sample",
    (_message.Message,),
    {
        "DESCRIPTOR": _SAMPLE,
        "__module__": "MeasuringSessionReportProto_pb2"
        # @@protoc_insertion_point(class_scope:biospectal.Sample)
    },
)
_sym_db.RegisterMessage(Sample)

RecordingData = _reflection.GeneratedProtocolMessageType(
    "RecordingData",
    (_message.Message,),
    {
        "DESCRIPTOR": _RECORDINGDATA,
        "__module__": "MeasuringSessionReportProto_pb2"
        # @@protoc_insertion_point(class_scope:biospectal.RecordingData)
    },
)
_sym_db.RegisterMessage(RecordingData)


DESCRIPTOR._options = None
_SAMPLE.fields_by_name["pixels"]._options = None
# @@protoc_insertion_point(module_scope)
